#!/usr/bin/env bash
# Keep nix-shell

if [[ -z $IN_NIX_SHELL ]]; then
    swaymsg -t command exec "alacritty --working-directory $PWD"
else
    swaymsg -t command exec "alacritty --working-directory $PWD --command nix-shell --run zsh"
fi

